# Generated by Django 4.2.7 on 2025-11-07 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_enhanced_task_model'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='task',
            name='tasks_completed_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='task',
            name='tasks_priority_due_date_idx',
        ),
    ]
